[programs.localnet]
nft_staker = "4i81fhenGRc5566CPQUEZaiG21ZMk93VyxuvWbjQ9DXc"

[programs.devnet]
nft_staker = "4i81fhenGRc5566CPQUEZaiG21ZMk93VyxuvWbjQ9DXc"

[programs.mainnet]
nft_staker = "4i81fhenGRc5566CPQUEZaiG21ZMk93VyxuvWbjQ9DXc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./lib/SEA1xkZzPCUJBb5mcNb6ts9VExNr2kYMit3T5poqr94.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
